### ISSUE TITLE
在README界面截图下注释pixiv id

### ISSUE THREAD

**Issue by poly000** [xiao-cao-x/pixiv_func_android#2]

**Comment by xiao-cao-x** [comment]
具体什么意思 没懂

**Comment by xiao-cao-x** [comment]
你指的是pixiv id ?

**Comment by poly000** [comment]
> 你指的是pixiv id ?

现在只找到第一张截图的 90703043

**Comment by xiao-cao-x** [comment]
> > 你指的是pixiv id ?
> 
> 现在只找到第一张截图的 90703043

90703043怎么了

**Comment by poly000** [comment]
> > > 你指的是pixiv id ?
> > 
> > 
> > 现在只找到第一张截图的 90703043
> 
> 90703043怎么了

啊这…… 这个issue应该只算一个question
主要是问问readme截图中的色图的id 好下载

**Comment by xiao-cao-x** [comment]
> 啊这…… 这个issue应该只算一个question 主要是问问readme截图中的色图的id 好下载

嗷 这样啊。 我的软件继承了搜图功能

**Comment by xiao-cao-x** [comment]
![image](https://user-images.githubusercontent.com/76673990/135711681-ba13a655-9bb4-4760-93a4-e84b718ee40b.png)

合你XP的话 可以搜我id 72269198

**Comment by poly000** [comment]
> 72269198

谢谢 关注了

**Comment by xiao-cao-x** [comment]
我在写本地历史记录呢 突然看到邮件提示 我的库有个issue 哈哈

**Comment by poly000** [comment]
> 我在写本地历史记录呢 突然看到邮件提示 我的库有个issue 哈哈

嘿嘿 虽然可能只算discussion（）

**Comment by xiao-cao-x** [comment]
> 嘿嘿 虽然可能只算discussion（）

我不太会用git
突然看到多了几个star 有点受宠若惊的感觉...

**Comment by poly000** [comment]
> > 嘿嘿 虽然可能只算discussion（）
> 
> 我不太会用git 突然看到多了几个star 有点受宠若惊的感觉...

emmm 我好像是刚刚在arch nsfw看到你的仓库的
界面看上去就很好看

**Comment by xiao-cao-x** [comment]
> emmm 我好像是刚刚在arch nsfw看到你的仓库的 界面看上去就很好看

arch nsfw 是什么 github的推荐嘛?

**Comment by poly000** [comment]
> > emmm 我好像是刚刚在arch nsfw看到你的仓库的 界面看上去就很好看
> 
> arch nsfw 是什么 github的推荐嘛?

arch nsfw是archlinux ot群附属nsfw群

**Comment by xiao-cao-x** [comment]
> arch nsfw是archlinux ot群附属nsfw群

不懂, 但是好奇为什么我的库会在那里看到
