### ISSUE TITLE
求pixiv_local_reverse_proxy.aar的使用方式

### ISSUE THREAD

**Issue by mouyase** [xiao-cao-x/pixiv_func_android#4]
我也是app开发者，想要了解一下这个库如何使用，希望可以得到指点，谢谢

**Comment by xiao-cao-x** [comment]
![image](https://user-images.githubusercontent.com/76673990/145546651-cb31fc80-f0f4-49ec-b965-42efcd393a13.png)
![image](https://user-images.githubusercontent.com/76673990/145546672-e66fecfb-40b9-4639-b2be-ec79195431bf.png)

**Comment by xiao-cao-x** [comment]
启动
```kotlin
PixivLocalReverseProxy.startServer("12345")
```
停止
```kotlin
PixivLocalReverseProxy.stopServer()
```
见[PlatformWebView.kt](https://github.com/xiao-cao-x/pixiv_func_android/blob/main/android/app/src/main/kotlin/top/xiaocao/pixiv/platform/webview/PlatformWebView.kt)

**Comment by mouyase** [comment]
![image](https://user-images.githubusercontent.com/7844572/145548484-07d992af-250c-406a-9dc7-bf89a30f5559.png)
看起来应该是这样，但是并不能成功访问，所以不知道问题出在了哪里

**Comment by xiao-cao-x** [comment]
> 看起来应该是这样，但是并不能成功访问，所以不知道问题出在了哪里  

看看Log打印是否正常
可能是与运营商(地区)有关
你可以下载我的APK试试能否登录

**Comment by mouyase** [comment]
您的app可以正常登陆，所以问题是在我这里。

这个只要将代理设置好，然后直接访问www.pixiv.net就可以实现直连吗，是否需要处理证书或其他的问题呢

**Comment by mouyase** [comment]
付log
![image](https://user-images.githubusercontent.com/7844572/145549493-597ac050-70f6-4bae-9109-8214b45ede03.png)

**Comment by xiao-cao-x** [comment]
![image](https://user-images.githubusercontent.com/76673990/145549831-b4516e19-ae39-4481-b87f-afc9e9d8056d.png)

**Comment by mouyase** [comment]
大佬牛逼，已经完全可以使用了

**Comment by xiao-cao-x** [comment]
> 大佬牛逼，已经完全可以使用了

Q群 可加693412468
