### ISSUE TITLE
保存图片问题

### ISSUE THREAD

**Issue by VCE1** [xiao-cao-x/pixiv_func_android#6]
软件版本0.12.4
安卓9系统
软件存储权限给了。我在保存图片后提示保存成功，但是去相册一看却空空如也，好几个版本都有这种问题，起初还以为是手机问题，去浏览器下个图片却成功出现在相册里。有时候可以正常保存，但有很大概率触发这个问题

**Comment by xiao-cao-x** [comment]
> 软件版本0.12.4
> 安卓9系统
> 软件存储权限给了。我在保存图片后提示保存成功，但是去相册一看却空空如也，好几个版本都有这种问题，起初还以为是手机问题，去浏览器下个图片却成功出现在相册里。有时候可以正常保存，但有很大概率触发这个问题

下载成功但是不显示在相册可能是没有广播的问题，文件夹里应该是有的。
我的红米9 安卓11一直都可以正常显示的，你是什么品牌的手机? 我回头加个广播

**Comment by xiao-cao-x** [comment]
我看了下 确实是没加广播的问题 Android.Q(10以上) 是查询数据库通过uri插入的 而10以下都是直接写文件的，这个我只在模拟器里测试过 因为我没有10以下的机器

**Comment by xiao-cao-x** [comment]
试试[这个版本](https://github.com/xiao-cao-x/pixiv_func_android/releases/tag/0.13.0)
看看保存图片能不能立即显示在系统相册中

**Comment by xiao-cao-x** [comment]
@VCE1 快试试

**Comment by VCE1** [comment]
试了可以了！

**Comment by xiao-cao-x** [comment]
好的😋
